theme: jekyll-theme-minimal
title: Academic Website of Ted Laderas
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Ted Laderas
  avatar: bio-photo.jpg
  
  
title: Welcome
description: just trying things out
picture: './head_shot.jpg'
picture: /head_shot.jpg
description: just trying things out

owner: 
  name: Alexander
  avatar: head_shot.jpg
  bio: Welcome to my page. My name is Alexander and I am doing neuro-psychology research at...
  email: alexander@gmail.com
  location: Sunflower Field, USA
